# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#What branch we are watching
trigger:
  - 'master'

pool: 'ubuntu-latest'

variables:
- name: 'instructor'
  value: 'Mark'

#watch for PR's
pr: 'none'

#groups sequential actions
stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          - script: 'dotnet build'
          - script: echo Hey there $(instructor)!
      - job: 'test'
        dependsOn: 'build'
        steps:
          - script: 'dotnet test'
      - job: 'publish'
        dependsOn: 'test'
        steps:
          - script: 'dotnet publish'

name: '$(date:yyyyMMdd)$(rev:rr)'